name: Generate Plant UML Diagrams

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  read-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Read and process files
        id: read_files
        run: |
          # Create a temporary directory to store the generated SVGs
          mkdir -p svgs

          # Find all files in the docs directory and process each one
          for file in docs/*; do
            if [ -f "$file" ]; then
              file_name=$(basename "$file")
              file_content=$(cat "$file")
              svg_file="svgs/${file_name%.*}.svg"
              
              echo "Processing $file_name"
              
              # Save the file content to the output variable
              echo "file_name=$file_name" >> $GITHUB_ENV
              echo "file_content<<EOF" >> $GITHUB_ENV
              echo "$file_content" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV

              # POST to Kroki and save the response
              diagram_source=$(echo "$file_content")
              payload=$(jq -n --arg ds "$diagram_source" '{diagram_source: $ds}')
              curl -X POST https://kroki.io/plantuml/svg \
                -H "Content-Type: application/json" \
                -d "$payload" \
                -o "$svg_file"

              # Add the generated SVG to git
              git add "$svg_file"
            fi
          done

      - name: Commit SVG files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m 'Add generated SVG files from Kroki responses'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}