name: Generate Plant UML Diagrams

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  read-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read file content
        id: read_file
        run: |
          file_path="./docs/component.plantuml"
          if [ -f "$file_path" ]; then
            file_content=$(cat "$file_path")
            echo "file_content<<EOF" >> $GITHUB_OUTPUT
            echo "$file_content" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "File not found: $file_path"
            exit 1
          fi

      - name: Display file content
        run: echo "${{ steps.read_file.outputs.file_content }}"
      - name: POST to Kroki
        run: |
          diagram_source=$(echo "${{ steps.read_file.outputs.file_content }}")
          payload=$(jq -n --arg ds "$diagram_source" '{diagram_source: $ds}')
          curl -X POST https://kroki.io/plantuml/svg \
            -H "Content-Type: application/json" \
            -d "$payload" \
            -o file.svg
        env:
          file_content: ${{ steps.read_file.outputs.file_content }}
      - name: Commit file.svg
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add file.svg
          git commit -m 'Add generated file.svg from Kroki response'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}